config/routes.rb
require 'sidekiq/web'

Hummingbird::Application.routes.draw do
  resources :library_entries, except: [:new, :edit]
  resources :manga_library_entries, except: [:new, :edit]
  resources :franchises, only: [:index, :show]
  resources :full_anime, only: [:show, :update, :destroy]
  resources :full_manga, only: [:show, :update]
  resources :news_feeds, only: [:index]
  resources :quotes

  resources :stories do
    get :likers
  end

  resources :substories, only: [:index, :create, :destroy]
  resources :user_infos, only: [:show]
  resources :changelogs, only: [:index]

  resources :reviews do
    post :vote
  end

  get '/apps/mine' => 'apps#mine'
  resources :apps

  resource :chat, only: [:show, :create, :destroy] do
    post :ping
  end

  devise_for :users, skip: [:sessions, :registrations], controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  # sessions
  get '/sign-in' => 'home#static', as: :new_user_session
  post '/sign-in' => 'auth#sign_in_action', as: :user_session
  match '/sign-out' => 'auth#sign_out_action', as: :destroy_user_session,
    via: [:post, :delete]

  # registrations
  get '/sign-up' => 'home#static', as: :new_user_registration
  post '/sign-up' => 'auth#sign_up_action', as: :user_registration
  get '/users/edit', to: redirect('/settings'), as: :edit_user_registration

  # redirects if there happens to be any outdated links around the web
  get '/users/sign_in', to: redirect('/sign-in')
  get '/users/sign_up', to: redirect('/sign-up')

  resources :notifications, only: [:index, :show]

  namespace :community do
    get '/' => 'forums#index'
    resources :forums do
      resources :topics
    end
  end

  namespace :api do
    namespace :v2 do
      resources :anime
    end
  end

  get '/privacy' => 'home#static'
  get '/branding' => 'home#static'

  # Recommendations
  get '/recommendations' => 'recommendations#index'
  post '/recommendations/not_interested' => 'recommendations#not_interested'
  post '/recommendations/plan_to_watch' => 'recommendations#plan_to_watch'
  get '/recommendations/force_update' => 'recommendations#force_update'

  get '/unsubscribe/newsletter/:code' => 'home#unsubscribe'

  root :to => "home#index"

  # Dashboard
  get '/dashboard' => 'home#dashboard'

  get '/onboarding(/:id)' => 'home#static'

  get '/pro' => 'home#static'
  resources :pro_membership_plans, only: [:index]
  resources :pro_memberships, only: [:create, :destroy]
  resources :partner_deals, only: [:index, :update]

  get '/u/:id' => redirect {|params| "/users/#{params[:id]}" }
  get '/a/:id' => redirect {|params| "/anime/#{params[:id]}" }
  get '/m/:id' => redirect {|params| "/manga/#{params[:id]}" }
  get '/g/:id' => redirect {|params| "/groups/#{params[:id]}" }

  get '/users/to_follow' => 'users#to_follow' # public endpoint for users to follow

  resources :users, only: [:index, :show, :update] do
    get 'library/manga' => 'users#ember'
    get 'library' => 'users#ember'
    get 'groups' => 'users#ember'
    get 'reviews' => 'users#ember'
    get 'followers' => 'users#ember'
    get 'following' => 'users#ember'

    get 'feed' => redirect {|params| "/users/#{params[:id]}" }
    get 'watchlist' => redirect {|params| "/users/#{params[:id]}/library" }

    resources :lists

    put "/avatar" => 'users#update_avatar', as: :avatar

    post :follow
    post :comment

    post "/disconnect/facebook" => 'users#disconnect_facebook',
      as: :disconnect_facebook
  end

  # Favorite media
  resources :favorites
  post '/favorites/update_all' => 'favorites#update_all'

  resources :groups do
    get 'members' => 'groups#show', on: :member
  end

  resources :group_members

  # Settings
  get '/settings' => 'settings#index'
  namespace :settings do
    post :resend_confirmation

    # Legacy routes
    get 'backup/:action', to: 'backup'
    # New routes
    # Download
    get 'backup/download' => 'backup#download'
    # Dropbox
    get 'backup/dropbox' => 'backup#dropbox_connect'
    post 'backup/dropbox' => 'backup#dropbox'
    delete 'backup/dropbox' => 'backup#dropbox_disconnect'

    # Imports
    post 'import/myanimelist' => 'import#myanimelist'
  end

  # Search
  get '/search' => 'search#search'

  # Imports
  post '/mal_import', to: redirect('/settings/import/myanimelist')

  # Random anime
  get '/random/anime' => 'anime#random'
  get '/anime/upcoming(/:season)' => 'anime#upcoming', as: :anime_season
  get '/anime/filter(/:sort)' => 'anime#filter', as: :anime_filter

  resources :castings, only: [:index]

  resources :anime, only: [:show, :index, :update] do
    resources :quotes
    resources :reviews
    resources :episodes
  end

  resources :manga, only: [:index, :show]

  resources :genres, only: [:index, :show] do
    post :add_to_favorites
    post :remove_from_favorites
  end

  resources :characters, only: [:show]

  # Versions
  resources :versions, except: [:new, :create, :show]
  get '/edits' => 'versions#index'

  # Admin Panel
  constraints(lambda do |req|
    user = Auth::CurrentUserProvider.new(req.env).current_user
    user && user.admin?
  end) do
    get '/kotodama' => 'admin#index', as: :admin_panel
    get '/kotodama/stats' => 'admin#stats'
    get '/kotodama/login_as' => 'admin#login_as_user'
    get '/kotodama/find_or_create_by_mal' => 'admin#find_or_create_by_mal'
    get '/kotodama/users_to_follow' => 'admin#users_to_follow'
    get '/kotodama/users_to_follow_submit' => 'admin#users_to_follow_submit'
    get '/kotodama/blotter_set' => 'admin#blotter_set'
    get '/kotodama/blotter_clear' => 'admin#blotter_clear'
    post '/kotodama/deploy' => 'admin#deploy'
    post '/kotodama/publish_update' => 'admin#publish_update'
    post '/kotodama/reset_break_counter' => 'admin#reset_break_counter'
    post '/kotodama/refill_codes' => 'admin#refill_codes'

    mount Sidekiq::Web => '/kotodama/sidekiq'
    mount RailsAdmin::Engine => '/kotodama/rails_admin', as: 'rails_admin'
    mount PgHero::Engine => '/kotodama/pghero'
    mount Kibana::Rack::Web => '/kibana'
  end

  mount API => '/'

  # Ember Tests
  mount EmberCLI::Engine => 'ember-tests' if Rails.env.development?
end

app/models/quote.rb
# == Schema Information
#
# Table name: quotes
#
#  id             :integer          not null, primary key
#  anime_id       :integer
#  content        :text
#  character_name :string(255)
#  user_id        :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  positive_votes :integer          default(0), not null
#

class Quote < ActiveRecord::Base
  belongs_to :anime
  belongs_to :user

  has_many :substories, as: :target, dependent: :destroy

  def creator
    user
  end

  validates :content, :anime, :user, :presence => true
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @anime = Anime.find(params[:anime_id])
    @quotes = @anime.quotes.includes(:user).order('positive_votes DESC')

    respond_to do |format|
      format.html do
        preload_to_ember! @anime, serializer: FullAnimeSerializer, root: "full_anime"
        render_ember
      end
      format.json do
        render json: @quotes
      end
    end
  end

  def create
    authenticate_user!

    quote_params = params.require(:quote).permit(:anime_id, :character_name, :content)

    anime = Anime.find(quote_params[:anime_id])
    quote = Quote.create(
      character_name: quote_params[:character_name],
      content: quote_params[:content],
      anime: anime,
      user: current_user
    )

    render json: quote
  end

  def update
    authenticate_user!

    quote = Quote.find(params[:id])

    # Update favorite status.
    vote = Vote.for(current_user, quote)
    if params[:quote]["is_favorite"]
      if vote.nil?
        Vote.create(user: current_user, target: quote)
      end
    else
      unless vote.nil?
        vote.destroy!
      end
    end

    render json: quote.reload
  end
end

app/views/quotes/_new.html.haml
:css
  .twitter-typeahead .tt-dropdown-menu {
    left: 0px !important;
    width: 100% !important;
    top: 32px !important;
  }

%h3 New "#{@anime.canonical_title(current_user)}" quote

= form_for Quote.new, :url => anime_quotes_path(@anime) do |f|
  = f.label :content
  = f.text_area :content, rows: 5

  = f.label :character
  = f.text_field :character_name, class: "#{@anime.slug}_character_name"

  = f.submit class: "button padded"

:javascript
  $("input.#{@anime.slug}_character_name").typeahead({
    name: '#{@anime.slug}_character_name',
    prefetch: '#{anime_casts_url(@anime, type: 'character_names', format: :json)}',
    local: #{@anime.castings.where(featured: true).includes(:character).select {|x| x.character_id }.map {|x| x.character.name }.map {|x| x.strip }.uniq.to_json}
  });

app/views/quotes/_votes.html.haml
%span{:class => "quote_#{quote.id}_votes"}
  = pluralize quote.positive_votes.to_i, "likes"
  - if current_user && current_user.voted_for?(quote)
    = link_to main_app.vote_anime_quote_path(quote.anime_id, quote, type: "down"), method: :post, remote: true do
      %i.fa.fa-star
  - else
    = link_to main_app.vote_anime_quote_path(quote.anime_id, quote, type: "up"), method: :post, remote: true do
      %i.fa.fa-star-o

app/views/quotes/index.html.haml
.anime-discover.anime-show.anime-show-full.quote-page
  .row
    .large-2.columns.no-padding
      .quote-thumb
        = image_tag @anime.poster_image.url(:large), alt: @anime.canonical_title(current_user)
        - if false
          .large-12.columns.no-padding
            %a.small.button.split.padded{:href => "#"}
              Want to Watch
              %span{"data-dropdown" => "drop1"}
            %ul#drop1.f-dropdown.watchlist-button{"data-dropdown-content" => ""}
              %li
                %a{:href => "#"} Currently Watching
              %li
                %a{:href => "#"} Completed
              %li
                %a{:href => "#"} On Hold
              %li
                %a{:href => "#"} Dropped
              %li
                %a{:href => "#"} Remove 

    .large-7.columns.center-column
      .panel.center
        %h4.center= title "#{@anime.canonical_title(current_user)} Quotes"
        %hr
        = link_to "Back to Anime Page", anime_path(@anime)
        or
        %a{"data-reveal-id" => "submit-quote", :href => "#"}
          %span= "Submit New Quote"


          
      - @quotes.each do |quote|
        .large-12.columns.panel.no-padding.rounded-panel
          .large-12.columns.panel-head
            %p.head-title
              - if quote.creator
                Submitted by #{link_to quote.creator.name, quote.creator}
                |
              %a.tip-top(href="javascript:void(0)" data-tooltip title="Coming soon!") report
            %p.head-action
              = render partial: "quotes/votes", locals: {quote: quote}
          %hr.block-divider
          .large-12.columns
            %p.quote-content
              = quote.content
              - if quote.character_name
                %cite &mdash; #{quote.character_name}

    .large-3.columns
      %h5 SCREENCAPS
      - @gallery.each do |gallery|
        = image_tag gallery.image.url(:thumb)

#submit-quote.reveal-modal{:class => "medium"}
  = render 'quotes/new'

app/views/quotes/replace_votes.js.erb
$(".quote_<%= @quote.id %>_votes").replaceWith('<%= j render(partial: 'quotes/votes', locals: {quote: @quote}) %>');