config/routes.rb
require 'sidekiq/web'

Hummingbird::Application.routes.draw do
  resources :library_entries, except: [:new, :edit]
  resources :manga_library_entries, except: [:new, :edit]
  resources :franchises, only: [:index, :show]
  resources :full_anime, only: [:show, :update, :destroy]
  resources :full_manga, only: [:show, :update]
  resources :news_feeds, only: [:index]
  resources :quotes

  resources :stories do
    get :likers
  end

  resources :substories, only: [:index, :create, :destroy]
  resources :user_infos, only: [:show]
  resources :changelogs, only: [:index]

  resources :reviews do
    post :vote
  end

  get '/apps/mine' => 'apps#mine'
  resources :apps

  resource :chat, only: [:show, :create, :destroy] do
    post :ping
  end

  devise_for :users, skip: [:sessions, :registrations], controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  # sessions
  get '/sign-in' => 'home#static', as: :new_user_session
  post '/sign-in' => 'auth#sign_in_action', as: :user_session
  match '/sign-out' => 'auth#sign_out_action', as: :destroy_user_session,
    via: [:post, :delete]

  # registrations
  get '/sign-up' => 'home#static', as: :new_user_registration
  post '/sign-up' => 'auth#sign_up_action', as: :user_registration
  get '/users/edit', to: redirect('/settings'), as: :edit_user_registration

  # redirects if there happens to be any outdated links around the web
  get '/users/sign_in', to: redirect('/sign-in')
  get '/users/sign_up', to: redirect('/sign-up')

  resources :notifications, only: [:index, :show]

  namespace :community do
    get '/' => 'forums#index'
    resources :forums do
      resources :topics
    end
  end

  namespace :api do
    namespace :v2 do
      resources :anime
    end
  end

  get '/privacy' => 'home#static'
  get '/branding' => 'home#static'

  # Recommendations
  get '/recommendations' => 'recommendations#index'
  post '/recommendations/not_interested' => 'recommendations#not_interested'
  post '/recommendations/plan_to_watch' => 'recommendations#plan_to_watch'
  get '/recommendations/force_update' => 'recommendations#force_update'

  get '/unsubscribe/newsletter/:code' => 'home#unsubscribe'

  root :to => "home#index"

  # Dashboard
  get '/dashboard' => 'home#dashboard'

  get '/onboarding(/:id)' => 'home#static'

  get '/pro' => 'home#static'
  resources :pro_membership_plans, only: [:index]
  resources :pro_memberships, only: [:create, :destroy]
  resources :partner_deals, only: [:index, :update]

  get '/u/:id' => redirect {|params| "/users/#{params[:id]}" }
  get '/a/:id' => redirect {|params| "/anime/#{params[:id]}" }
  get '/m/:id' => redirect {|params| "/manga/#{params[:id]}" }
  get '/g/:id' => redirect {|params| "/groups/#{params[:id]}" }

  get '/users/to_follow' => 'users#to_follow' # public endpoint for users to follow

  resources :users, only: [:index, :show, :update] do
    get 'library/manga' => 'users#ember'
    get 'library' => 'users#ember'
    get 'groups' => 'users#ember'
    get 'reviews' => 'users#ember'
    get 'followers' => 'users#ember'
    get 'following' => 'users#ember'

    get 'feed' => redirect {|params| "/users/#{params[:id]}" }
    get 'watchlist' => redirect {|params| "/users/#{params[:id]}/library" }

    resources :lists

    put "/avatar" => 'users#update_avatar', as: :avatar

    post :follow
    post :comment

    post "/disconnect/facebook" => 'users#disconnect_facebook',
      as: :disconnect_facebook
  end

  # Favorite media
  resources :favorites
  post '/favorites/update_all' => 'favorites#update_all'

  resources :groups do
    get 'members' => 'groups#show', on: :member
  end

  resources :group_members

  # Settings
  get '/settings' => 'settings#index'
  namespace :settings do
    post :resend_confirmation

    # Legacy routes
    get 'backup/:action', to: 'backup'
    # New routes
    # Download
    get 'backup/download' => 'backup#download'
    # Dropbox
    get 'backup/dropbox' => 'backup#dropbox_connect'
    post 'backup/dropbox' => 'backup#dropbox'
    delete 'backup/dropbox' => 'backup#dropbox_disconnect'

    # Imports
    post 'import/myanimelist' => 'import#myanimelist'
  end

  # Search
  get '/search' => 'search#search'

  # Imports
  post '/mal_import', to: redirect('/settings/import/myanimelist')

  # Random anime
  get '/random/anime' => 'anime#random'
  get '/anime/upcoming(/:season)' => 'anime#upcoming', as: :anime_season
  get '/anime/filter(/:sort)' => 'anime#filter', as: :anime_filter

  resources :castings, only: [:index]

  resources :anime, only: [:show, :index, :update] do
    resources :quotes
    resources :reviews
    resources :episodes
  end

  resources :manga, only: [:index, :show]

  resources :genres, only: [:index, :show] do
    post :add_to_favorites
    post :remove_from_favorites
  end

  resources :characters, only: [:show]

  # Versions
  resources :versions, except: [:new, :create, :show]
  get '/edits' => 'versions#index'

  # Admin Panel
  constraints(lambda do |req|
    user = Auth::CurrentUserProvider.new(req.env).current_user
    user && user.admin?
  end) do
    get '/kotodama' => 'admin#index', as: :admin_panel
    get '/kotodama/stats' => 'admin#stats'
    get '/kotodama/login_as' => 'admin#login_as_user'
    get '/kotodama/find_or_create_by_mal' => 'admin#find_or_create_by_mal'
    get '/kotodama/users_to_follow' => 'admin#users_to_follow'
    get '/kotodama/users_to_follow_submit' => 'admin#users_to_follow_submit'
    get '/kotodama/blotter_set' => 'admin#blotter_set'
    get '/kotodama/blotter_clear' => 'admin#blotter_clear'
    post '/kotodama/deploy' => 'admin#deploy'
    post '/kotodama/publish_update' => 'admin#publish_update'
    post '/kotodama/reset_break_counter' => 'admin#reset_break_counter'
    post '/kotodama/refill_codes' => 'admin#refill_codes'

    mount Sidekiq::Web => '/kotodama/sidekiq'
    mount RailsAdmin::Engine => '/kotodama/rails_admin', as: 'rails_admin'
    mount PgHero::Engine => '/kotodama/pghero'
    mount Kibana::Rack::Web => '/kibana'
  end

  mount API => '/'

  # Ember Tests
  mount EmberCLI::Engine => 'ember-tests' if Rails.env.development?
end

app/views/shared/_footer.html.haml
.hummingbird-footer

  - unless @hide_footer_ad
    .large-12.columns.footer-ad.hide-for-small
      %ins(class="adsbygoogle" style="display:inline-block;width:728px;height:90px" data-ad-client="ca-pub-3410319844519574" data-ad-slot="4888559644")
      :javascript
        (adsbygoogle = window.adsbygoogle || []).push({});

  .bottom-bar
    %footer.row
      .large-12.columns
        .row.footer
          .large-6.columns
            .large-12.columns
              %ul.inline-list{:style => "margin-bottom: 0px;"}
                %li.hide-for-small= link_to "About", "#"
                %li= link_to "Explore", "/anime"
                %li= link_to "Dashboard", user_signed_in? ? main_app.user_path(current_user) : "/users/sign_in"
                %li= link_to "Community", "https://forums.hummingbird.me/"

            .large-12.columns
              %ul.inline-list{:style => "opacity: .5; font-size: 12px;"}
                %li.hide-for-small &copy; 2015 Hummingbird.me
                %li= link_to "Terms", "#"
                %li= link_to "Privacy", "/privacy"
                %li= link_to "Contact", "mailto:josh@hummingbird.me"

          .large-6.columns
            .large-12.columns.hide-for-small
              %ul.inline-list.right
                %li
                  .fb-like{"data-href" => "https://www.facebook.com/pages/Hummingbird/460188747373182?ref=hl", "data-layout" => "button_count", "data-send" => "false", "data-show-faces" => "true", "data-width" => "450"}
                %li{:style => "background: none; width: 87px;"}
                  %a.twitter-share-button{"data-text" => "Hummingbird is a new and easy way to find anime titles you'll love. #anime", "data-url" => "https://hummingbird.me", "data-via" => "Hummingbird_me", :href => "https://twitter.com/share"} Tweet

app/views/shared/_forum_widget.html.haml
:css
  .sotm img {max-width: 90%;}

.large-12.columns.no-padding.forum-block.rounded-panel.hide-for-small
  %ul.sotm{:style => "text-align: center; padding-top: 15px;"}
    = link_to "https://hummingbird.me/2013/" do
      = image_tag "http://i.imgur.com/C36CvjG.jpg"

app/views/shared/_header.html.haml
.hummingbird-header-1
  .hummingbird-header-actual.fixed.nav-attached
    .contain-to-grid.rounded-panel
      %nav.top-bar.cf
        %ul.title-area
          %li.name
            = link_to image_tag("https://hummingbird.me/assets/logo-new.jpg", :height => "20px", :width => "119px"), "/"
          %li.toggle-topbar.menu-icon
            %a{:href => "#"}
              %span Menu
        %section.top-bar-section
          / Left Nav Section
          %ul.left.topnav-links
            %li.has-dropdown
              = link_to "Library", "#"
              %ul.dropdown.rounded-panel
                %li
                  = link_to "Anime Library", user_signed_in? ? main_app.user_library_path(current_user) : "/sign-in"
                %li
                  = link_to "Manga Library", user_signed_in? ? "/users/#{current_user.name}/library/manga" : "/sign-in"
                %li
                  = link_to "Recommendations", '/recommendations'
            %li.has-dropdown
              %a{:href => "/anime"} Explore
              %ul.dropdown.rounded-panel
                %li
                  // change me to upcoming link
                  = link_to "Upcoming", main_app.anime_season_path
            %li
              = link_to "Community", "https://forums.hummingbird.me/"

          / Right Nav Section
          %ul.right.right-top-nav
            %li.has-form.search-form
              .row.collapse.header-search
                .small-12.columns
                  %form#live_search_form{:action => "/search", :autocomplete => "off"}
                    %input.typeahead#nav_search_input(type="text" name="query"){:placeholder => "Search...", :value => params[:query], :autocomplete => "off"}
                    %input#nav_search_submit.submit.ss-icon{:type => "submit", :value => "search"}

            %li.divider.show-for-small
            - if user_signed_in?
              %li.notification-block.has-dropdown
                %a.notification-button{href: "/notifications", class: ("active" if Notification.unseen_count(current_user) > 0)}
                  %i.fa.fa-bell-o
                    - if Notification.unseen_count(current_user) > 0
                      %span.notification-count= "%02d" % Notification.unseen_count(current_user)

                %ul.dropdown.rounded-panel
                  = render partial: "notifications/notification", collection: Notification.recent_notifications(current_user)
                  %li
                    %a.view-all-notifications.single-notification.large-12.columns.center(href="/notifications")
                      view all

              %li.user-block.has-dropdown
                = link_to image_tag(current_user.avatar_url, :class => "avatar"), main_app.user_path(current_user), :class => "avatar-link-selector"
                %ul.dropdown.rounded-panel
                  %li
                    = link_to "View Profile", main_app.user_path(current_user)
                  %li
                    = link_to "Settings", main_app.edit_user_registration_path
                  - if current_user.admin?
                    %li 
                      = link_to "Admin panel", "/kotodama"
                  %li
                    = link_to "Sign out", main_app.destroy_user_session_path, :method => :delete
            - else
              %li.guest-block
                %span 
                  %a{href: "/sign-in"} Sign In
                  or 
                  %a{href: "/sign-up"} Create an Account

    - if not user_signed_in?
      .guest-banner.hide-for-small
        .large-12.columns
          = link_to "Hummingbird is the easiest way to track, share and discover new anime. Create an Account - Free.", "/sign-up"
          %span.guest-button= link_to "Request Invite", main_app.new_user_registration_path

    - if user_signed_in? and not current_user.confirmed?
      .guest-banner.hide-for-small
        .large-12.columns
          %a(data-tooltip data-width=500 title="You can confirm your email address by clicking on the link in the email you received after registration. If you didn't receive a confirmation email, click on the 'Resend Confirmation Email' button.") Please confirm your email address.
          %span.guest-button= link_to "Resend Confirmation Email", new_confirmation_path(User)

  - flash.each do |style, message|
    .alert-box{:class => style.to_s}= message

app/views/shared/_sign_in_modal.html.haml
.reveal-modal.small#signInModal
  %p.lead Welcome back, we missed you.
  %a.close-reveal-modal &#215;
  = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
    .row
      .small-12.columns
        = f.email_field :email, placeholder: 'Email Address'
        = f.password_field :password, placeholder: 'Password'
        = hidden_field_tag :return_to, request.original_url
        = f.submit "Login", class: 'button small pull-right'

        .pull-left.forgot-password
          = link_to "Forgot your password?", new_password_path(resource_name)

        .alternate-label 
          %span or
          %hr

        = link_to omniauth_authorize_path(resource_name, :facebook), class: 'fb-button' do
          %i.fa.fa-facebook
          %span Login with Facebook

        %hr
        %ul.links
          %li
            Don't have an account?
            = link_to "Create one now.", new_registration_path(resource_name)